server:
  port: 8082

spring:
  datasource:
    url: "${PROFILE_DB_URL}"
    username: "${PROFILE_DB_USERNAME}"
    password: "${PROFILE_DB_PASSWORD}"
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  rabbitmq:
      host: localhost
      port: 5672
      username: "${RABBITMQ_DEFAULT_USER}"
      password: "${RABBITMQ_DEFAULT_PASS}"
      listener:
        simple:
          retry:
            enabled: true
            initial-interval: 1000
            max-attempts: 3
            multiplier: 1.0
            max-interval: 10000
  
app:
  rabbitmq:
    userExchange: "${USER_CREATION_EXCHANGE}"
    userCreatedRoutingKey: "${USER_CREATED_ROUTING_KEY}"
    userCreatedQueue: "${USER_CREATED_QUEUE}"
    userResponseQueue: "${USER_RESPONSE_QUEUE}"