server:
  http_listen_port: 3200

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: "0.0.0.0:4317"
        http:
          endpoint: "0.0.0.0:4318"

storage:
  trace:
    backend: local
    wal:
      path: /var/lib/tempo/wal
    local:
      path: /var/lib/tempo/blocks

compactor:
  compaction:
    block_retention: 48h
    compacted_block_retention: 1h

ingester:
  trace_idle_period: 10s
  max_block_bytes: 100000
  max_block_duration: 5m